In [3]:
import pandas as pd

In [2]:
pd. __version__

'3.0.5'

In [ ]:
scores = pd.Series([38,54,31], index=["Dipta","Abid","Hamid"]) ### creating  series using index
print(scores)

marks = {
    "Rahim":35,
    "Karim":99,
    "Shafiq":67
}

Numbers = pd.Series(marks) ### creating series from an existing dictionary
print(Numbers)

Dipta    38
Abid     54
Hamid    31
dtype: int64
Rahim     35
Karim     99
Shafiq    67
dtype: int64

In [9]:
### useful attributes

print(Numbers.values)
print(Numbers.index)
print(Numbers.dtype)

[35 99 67]
Index(['Rahim', 'Karim', 'Shafiq'], dtype='str')
int64

In [ ]:
data = {
    "name":["Dipta","Abid","Hamid"],
    "id":[1084,1119,1112],
    "marks":[67,87,90]
}

df = pd.DataFrame(data, index=["s1","s2","s3"]) # Created a dataframe using a dictionary of lists with row info 
df

     name    id  marks
s1  Dipta  1084     67
s2   Abid  1119     87
s3  Hamid  1112     90

In [ ]:
data2 = [
    {"name":"Dipta","Scores":96},
    {"name":"Abid","Scores":90},
    {"name":"Hamid","Scores":91}
]

df2 = pd.DataFrame(data2)   # Created dataframe from a list of dictionaries

    name  Scores
0  Dipta      96
1   Abid      90
2  Hamid      91

In [14]:
data3 = [["Dipta","CSE","BDB"],["Abid","CSE","CTG"]]        # List of lists
df3 = pd.DataFrame(data3, columns=["name","dept","city"])   #creating df from list of lists and giving column names
df3

    name dept city
0  Dipta  CSE  BDB
1   Abid  CSE  CTG

In [26]:
print(df.shape)

print(df.columns)   #show column names

print(df.head(2))   #shows the number of records specified in the head() from the start

df.tail(1)          #shows the number of records from the end

print(df.dtypes)    # shows the datatypes of all columns, and it is in plural(dtypes)

print(df["name"])   # shows the values of the specific column mentioned

(3, 3)
Index(['name', 'id', 'marks'], dtype='str')
     name    id  marks
s1  Dipta  1084     67
s2   Abid  1119     87
name       str
id       int64
marks    int64
dtype: object
s1    Dipta
s2     Abid
s3    Hamid
Name: name, dtype: str